language: ruby
rvm:
  - 2.4.6

services:
  - mysql
  - docker

install:
  - cp config/database.yml.example config/database.yml
  - cp config/config.yml.example config/config.yml
  - cp db/schema.rb.example db/schema.rb
  - bundle install
  - bundle exec rake db:setup || bundle exec rake db:migrate

env:
  global:
    - RAILS_ENV=test
  matrix:
    - TASK="CI=true TRAVIS=true rake test:unit"
    - TASK="CI=true TRAVIS=true rake test:integration"
    - TASK="CI=true TRAVIS=true rake test:functional"
    - TASK="CI=true TRAVIS=true rake assets:precompile"
    - TASK="CI=true TRAVIS=true bundle exec rubocop"

jobs:
  include:
    - name: "Unit Tests"
      script: bundle exec rake test:unit
    - name: "Integration Tests"
      script: bundle exec rake test:integration
    - name: "Functional Tests"
      script: bundle exec rake test:functional
    - name: "Rubocop Linter"
      script: bundle exec rubocop
    - name: "Docker Builds"
      script: docker build -t mapknitter .
    - name: "Asset Precompilation"
      env:
        - RAILS_ENV=production
      script: bundle exec rake assets:precompile

branches:
  only:
    - main
    - unstable
    - development

